export const CLOSE_MODAL = "CLOSE_MODAL";
export const PROGRESS_MODAL = "PROGRESS_MODAL";
export const RESETPASSWORD_MODAL = "RESETPASSWORD_MODAL";
export const VERIFICATIONFAILED_MODAL = "VERIFICATIONFAILED_MODAL";
export const ACCOUNTVERIFIED_MODAL = "ACCOUNTVERIFIED_MODAL";
export const PROFILEUPDATED_MODAL = "PROFILEUPDATED_MODAL";
export const NOTIFICATIONUPDATED_MODAL = "NOTIFICATIONUPDATED_MODAL";
export const DELETE_TRANSACTION_MODAL = "DELETE_TRANSACTION_MODAL";
export const TRANSACTION_DELETED_MODAL = "TRANSACTION_DELETED_MODAL";
export const REJECT_TRANSACTION_MODAL = "REJECT_TRANSACTION_MODAL";
export const REJECT_TRANSACTION_REASON_MODAL =
  "REJECT_TRANSACTION_REASON_MODAL";
export const TRANSACTION_REJECTED_MODAL = "TRANSACTION_REJECTED_MODAL";
export const TRANSACTION_ACCEPTED_MODAL = "TRANSACTION_ACCEPTED_MODAL";
export const TRANSACTION_CANCELLED_MODAL = "TRANSACTION_CANCELLED_MODAL";
export const CONFIRM_TRANSACTION_MODAL = "CONFIRM_TRANSACTION_MODAL";
export const CANCEL_TRANSACTION_MODAL = "CANCEL_TRANSACTION_MODAL";
export const CANCEL_TRANSACTION_REASON_MODAL =
  "CANCEL_TRANSACTION_REASON_MODAL";
export const NEW_TRANSACTION_CREATED_MODAL = "NEW_TRANSACTION_CREATED_MODAL";
export const TRANSACTION_PAYMENT_MODAL = "TRANSACTION_PAYMENT_MODAL";
export const SUCCESS_TRANSACTION_PAYMENT_MODAL =
  "SUCCESS_TRANSACTION_PAYMENT_MODAL";
export const FAIL_TRANSACTION_PAYMENT_MODAL = "FAIL_TRANSACTION_PAYMENT_MODAL";
export const CONFIRM_DELIVERY_MODAL = "CONFIRM_DELIVERY_MODAL";
export const DELIVERY_CONFIRMED_MODAL = "DELIVERY_CONFIRMED_MODAL";
export const EMOJI_FORM_MODAL = "EMOJI_FORM_MODAL";
export const DELIVERY_FEEDBACK_MODAL = "DELIVERY_FEEDBACK_MODAL";
export const FEEDBACKSENT_MODAL = "FEEDBACKSENT_MODAL";
export const DISPUTE_SUBMITTED_MODAL = "DISPUTE_SUBMITTED_MODAL";
export const TRANSACTION_ITEM_MODAL = "TRANSACTION_ITEM_MODAL";
export const DISPUTE_ITEM_MODAL = "DISPUTE_ITEM_MODAL";
export const NEW_TRANSACTION_MODAL = "NEW_TRANSACTION_MODAL";
