export const SIGNUP_BIODATA = "SIGNUP_BIODATA"
export const SIGNUP_VERIFICATION = "SIGNUP_VERIFICATION"
export const SIGNUP_RESEND_VERIFICATION = "SIGNUP_RESEND_VERIFICATION"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"